[tool.poetry]
name = "airsenal"
version = "1.7.4"
description = "AI manager for Fantasy Premier League"
authors = [
	"Angus Williams <anguswilliams91@gmail.com>",
	"Jack Roberts <jroberts@turing.ac.uk>",
	"Nick Barlow <nbarlow@turing.ac.uk>",
]

[tool.poetry.dependencies]
python = ">=3.9,<3.12"
bpl = { git = "https://github.com/anguswilliams91/bpl-next", branch = "main" }
click = "^8.1.6"
pandas = "^2.0.3"
requests = "^2.31.0"
sqlalchemy = "^2.0.19"
tqdm = "^4.65.0"
dateparser = "^1.1.8"
prettytable = "^3.8.0"
beautifulsoup4 = "^4.12.2"
platformdirs = "^3.10.0"
jupyter = {version = "^1.0.0", optional = true}
matplotlib = {version = "^3.7.2", optional = true}
Flask = {version = "^2.3.2", optional = true}
numpyro = {version = "^0.12.1", optional = true}
seaborn = {version = "^0.12.2", optional = true}
python-dateutil = "^2.8.2"
lxml = "^4.9.3"
html5lib = "^1.1"
jax = "^0.4.14"
jaxlib = "^0.4.14"

[tool.poetry.group.dev.dependencies]
pytest-cov = "^4.1.0"
black = "^23.7.0"
isort = "^5.12.0"
flake8 = "^6.1.0"
pre-commit = "^3.3.3"
pytest = "^7.4.0"
pytest-sugar = "^0.9.7"
ipython = "8.12.1"  # Last for Python 3.8

[tool.poetry.extras]
api = ["Flask"]
notebook = ["jupyter"]
plot = ["matplotlib", "seaborn"]

[build-system]
requires = ["poetry-core>=1.0.0", "cython", "numpy", "setuptools"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
addopts = """
--cov=airsenal
--cov-report=term:skip-covered
--pdbcls=IPython.terminal.debugger:TerminalPdb
"""

[tool.isort]
profile = "black"

[tool.poetry.scripts]
airsenal_run_pipeline = "airsenal.scripts.airsenal_run_pipeline:run_pipeline"
airsenal_setup_initial_db = "airsenal.scripts.fill_db_init:main"
airsenal_update_db = "airsenal.scripts.update_db:main"
airsenal_run_prediction = "airsenal.scripts.fill_predictedscore_table:main"
airsenal_make_squad = "airsenal.scripts.squad_builder:main"
airsenal_run_optimization = "airsenal.scripts.fill_transfersuggestion_table:main"
airsenal_make_transfers = "airsenal.scripts.make_transfers:main"
airsenal_set_lineup = "airsenal.scripts.set_lineup:main"
airsenal_replay_season = "airsenal.scripts.replay_season:main"
airsenal_env = "airsenal.scripts.set_env:main"
airsenal_check_data = "airsenal.scripts.data_sanity_checks:run_all_checks"
airsenal_dump_api = "airsenal.scripts.dump_api:main"
airsenal_dump_db = "airsenal.scripts.dump_db_contents:main"
airsenal_scrape_transfermarkt = "airsenal.scripts.scrape_transfermarkt:main"
airsenal_plot = "airsenal.scripts.plot_league_standings:main"
